spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.206.62.172:3306/imooc_security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Drb.199519
    initialize: true
  freemarker:
    suffix: .html
  session:
    store-type: none





#配置自己的登录页面
#imooc:
#  security:
#    browser:
##      loginPage: /demo-signIn.html
#      LoginType: JSON
#    code:
#      image:
#        lenght: 6
#        width: 100
#        url: /user,/user/*