spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.206.62.172:3406/imooc_security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Drb.199519
    initialize: true
  freemarker:
    suffix: .html
  session:
    store-type: none
  redis:
    host: 123.206.62.172
    port: 6479

security:
  oauth2:
    client:
      clientId: imooc
      clientSecret: imoocsecret

#配置自己的登录页面
imooc:
  security:
    browser:
#      loginPage: /demo-signIn.html
      LoginType: JSON
    code:
      image:
        length: 6
        width: 100
        url: /user,/user/*
      sms:
        url: /user,/user/*
    social：
      qq:
        app-id:
        app-secret:
